[package]
edition = "2021"
name = "aoc2023"
version = "0.1.0"

[dependencies]
once_cell = "1.18.0"


[[bin]]
name = "day1"
path = "src/day1/day1.rs"

[profile.release]
debug = false
opt-level = 2
strip = true
lto = true
